language: cpp

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-${IDE_VERSION}-linux64.tar.xz
  - tar xf arduino-${IDE_VERSION}-linux64.tar.xz
  - sudo mv arduino-${IDE_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  
install:
#  - ln -s $PWD /usr/local/share/arduino/libraries/MicroDebug
  
script:
  - arduino --verify --board ${BOARD} $PWD/examples/DoorOpenerSketch.ino
#  - arduino --verify --board ${BOARD} $PWD/examples/LedDebug/LedDebug.ino
#  - arduino --verify --board ${BOARD} $PWD/examples/SerialDebug/SerialDebug.ino
  
notifications:
  email:
    on_success: change
    on_failure: change
    
env:
  global:
    - IDE_VERSION=1.8.8
  matrix:
    - BOARD=arduino:avr:uno IDE_VERSION=1.8.8
    - BOARD=arduino:esp:esp32
    - BOARD=arduino:esp:esp8266
